# Use official nvidia ROS 2 Humble image as base
FROM nvcr.io/nvidia/isaac/ros:x86_64-ros2_humble_f247dd1051869171c3fc53bb35f6b907

RUN rm -f /etc/apt/sources.list.d/yarn*.list || true

# Set noninteractive mode for APT
ENV DEBIAN_FRONTEND=noninteractive

# Env setup
ENV SHELL=/bin/bash
SHELL ["/bin/bash", "-c"]

# Install system dependencies
RUN apt-get update && apt-get install -y \
    locales \
    curl \
    git \
    && locale-gen en_US.UTF-8 \
    && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

# Add Intel RealSense repository (with lsb-release)
RUN apt-get update && apt-get install -y \
    gnupg \
    lsb-release \
    && curl -sSf https://librealsense.intel.com/Debian/librealsense.pgp | apt-key add - \
    && echo "deb https://librealsense.intel.com/Debian/apt-repo $(lsb_release -cs) main" > /etc/apt/sources.list.d/librealsense.list \
    && apt-get update \
    && rm -rf /var/lib/apt/lists/*

# Pré-reqs básicos
RUN apt-get update && apt-get install -y --no-install-recommends \
    librealsense2-utils \
    librealsense2-dev \
    librealsense2-dbg \
    udev \
    usbutils \
    python3-pip \
    python3-tk \
    # Moveit packages
    ros-humble-moveit \
    ros-humble-moveit-common \
    ros-humble-moveit-msgs \
    ros-humble-moveit-resources \
    ros-humble-moveit-ros-planning \
    ros-humble-moveit-ros-move-group \
    ros-humble-moveit-plugins \
    ros-humble-moveit-ros-perception \
    ros-humble-magic-enum \
    && rm -rf /var/lib/apt/lists/*

# Set up workspace
WORKDIR /home/spot-teleop/spot-ros2_ws

# Copy source code
COPY spot-ros2_ws/src /home/spot-teleop/spot-ros2_ws/src

# Execute installation script
RUN cd /home/spot-teleop/spot-ros2_ws/src/spot_ros2 && chmod +x install_spot_ros2.sh && ./install_spot_ros2.sh

# Install dependencies (skip unavailable packages)
RUN rosdep install --from-paths src --ignore-src -y -r --rosdistro=humble --skip-keys="ros-humble-warehouse-ros-mongo" || true

# Set environment variables for ROS Domain ID and other configs
ENV HOME=/home/spot-teleop
ENV USER=root

# Create bashrc with ROS setup
RUN echo 'source /opt/ros/humble/setup.bash' >> /root/.bashrc && \
    echo 'source /opt/ros/humble/setup.bash' >> /etc/bash.bashrc

RUN pip install --upgrade pip "setuptools==69.5.1" "wheel>=0.43" && \
    pip install setuptools_scm warp-lang ninja "numpy==2.2.6" "scipy==1.15.3" "trimesh==4.8.3" yourdfpy && \
    pip install --no-cache-dir --upgrade "sympy>=1.12" "mpmath>=1.3.0" --ignore-installed && \
    pip install bosdyn-api==5.0.1.2 bosdyn-client==5.0.1.2 bosdyn-core==5.0.1.2 bosdyn-mission==5.0.1.2 bosdyn-choreography-client==5.0.1.2

ENV CUDA_HOME=/usr/local/cuda
ENV CUDAToolkit_ROOT=/usr/local/cuda
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:${LD_LIBRARY_PATH}

RUN rm -rf /usr/local/include/google \
           /usr/local/lib/libprotobuf* \
           /usr/local/lib/libprotoc* \
           /usr/local/bin/protoc || true

RUN apt-get update && apt-get install -y \
    protobuf-compiler \
    libprotobuf-dev


# Set default command
CMD ["/bin/bash"]
