FROM osrf/ros:noetic-desktop-full

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    python3 \
    python3-pyqt5 \
    x11-apps \
    && rm -rf /var/lib/apt/lists/*

SHELL ["/bin/bash", "-c"]

CMD ["bash"]
