pipelines:
  full_stack:
    - name: core
      script: /home/nexus/spot-teleop/catkin_ws/src/rqt_interface/scripts/bringup/00_core.sh

    - name: sensors
      script: /home/nexus/spot-teleop/catkin_ws/src/rqt_interface/scripts/bringup/10_sensors.sh
      wait_for:
        ros_topic: /zed/left/image_rect_color
        process: core

    - name: mapping
      script: /home/nexus/spot-teleop/catkin_ws/src/rqt_interface/scripts/bringup/20_mapping.sh
      wait_for:
        ros_node: /nvblox_node
        process: core

    - name: planning
      script: /home/nexus/spot-teleop/catkin_ws/src/rqt_interface/scripts/bringup/30_planning.sh
      wait_for:
        ros_node: /move_group
        process: core
  base_only:
    - name: core
      script: /home/nexus/spot-teleop/catkin_ws/src/rqt_interface/scripts/bringup/00_core.sh

    - name: sensors
      script: /home/nexus/spot-teleop/catkin_ws/src/rqt_interface/scripts/bringup/10_sensors.sh
      wait_for:
        ros_topic: /zed/left/image_rect_color
        process: core

    - name: planning
      script: /home/nexus/spot-teleop/catkin_ws/src/rqt_interface/scripts/bringup/30_planning.sh
      wait_for:
        ros_node: /move_group
        process: core

  minimal:
    - name: core
      script: /home/nexus/spot-teleop/catkin_ws/src/rqt_interface/scripts/bringup/00_core.sh

    - name: planning
      script: /home/nexus/spot-teleop/catkin_ws/src/rqt_interface/scripts/bringup/30_planning.sh
      wait_for:
        ros_node: /move_group
        process: core