planning_scene_monitor:
  publish_planning_scene: true
  publish_geometry_updates: true
  publish_state_updates: true
  publish_transforms_updates: true
  octomap_frame: body
  octomap_resolution: 0.05   
  max_update_rate: 5.0

  sensors: [pointcloud_updater]

  pointcloud_updater:
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /collision_cloud
    max_range: 5.0
    frame_subsample: 1
    point_subsample: 1 
    padding_offset: 0.03
    padding_scale: 1.0
    filtered_cloud_topic: /moveit_filtered_cloud
