topics:
  -
    topic: /tf  # Topic name on both ROS 1 and ROS 2
    type: tf2_msgs/msg/TFMessage  # Type of topic to bridge
    queue_size: 1  # Queue size
    qos:
      durability: volatile
      reliability: reliable

  -
    topic: /tf_static  # Topic name on both ROS 1 and ROS 2
    type: tf2_msgs/msg/TFMessage  # Type of topic to bridge
    qos:
      history: keep_all
      durability: transient_local
      reliability: reliable

  -
    topic: /ee_goal_pose
    type: geometry_msgs/msg/PoseStamped
    queue_size: 1
    
  -
    topic: /monitored_planning_scene
    type: moveit_msgs/msg/PlanningScene
    queue_size: 1
    qos:
      durability: volatile
      reliability: reliable
